### PR TITLE
Gamelogic

### PR DESCRIPTION
**Pull request by lifesurfeit**
Setup basic events and event handlers.

### CODE REVIEW

**Comment by leighgarbs** [comment]
I don't think the *Handler.hpp files (like TransactionCheckHandler.hpp) will be very useful.  The EventManager works with EventDelegates, so you can only add EventDelegates, which have this form:

``` c++
typedef std::function<void(const EventInterface&)> EventDelegate;
```

If you try to add a delegate with a different signature (like say the one defined in TransactionCheckHandler.hpp), it won't build.  Is there something else you intended those to be used for?

This should mean that all our event handling functions have to have the signature of an EventDelegate (they have to take a const EventInterface&).  Then, to get at and use the subclass of EventInterface that was actually passed in one has to use dynamic_cast like so (this example uses the ActorMovedEvent):

``` c++
void actorMovedEventHandler(const EventInterface& event)                         
{                                                                                   
  const ActorMovedEvent* am_event = dynamic_cast<const ActorMovedEvent*>(&event);   

  /* dynamic_cast returns 0 if it couldn't successfully convert the EventInterface
      that was passed in into an ActorMovedEvent */                                         
  if (am_event == 0) return;

  /* now do whatever is needed with am_event */
}
```

**Comment by lifesurfeit** [comment]
Ok, I'll change them to EventDelegates. Thanks!

**Comment by mrfievel** [comment]
So just to be clear, that handler function would just be located in
whatever class wants to mess with that event?  Also, would the delegate be
used to bind the function and event in the class initialize?  If so, could
you possibly give a quick example of how that works?  Sorry, Im still a bit
hazy on how all the event manager stuff works, want to make sure I get it
right before we have to mash these things together.

**Comment by leighgarbs** [comment]
Well, I don't think we actually need any definition for event delegates besides the one we already have.  Really to use events the only new stuff that's needed is a function somewhere to handle the event (not the std::function kind defined in EventDelegate.hpp, just a normal function with the right signature) and the event itself.

**Comment by lifesurfeit** [comment]
Justin, did you manage to get the ShipMoveCmdEvent done?

**Comment by lifesurfeit** [comment]
I guess the problem I'm having right now is figuring out how to queue things onto the event manager if the delegates are void functions which I put inside of GameLogic.cpp. Another problem is comparing actors positions to the map - is the current view of the map supposed to be passed from the View? The view also interprets the real coordinates into the grid of the map, correct?  

Do you think we could meet sometime tomorrow after 4 to discuss this?

**Comment by mrfievel** [comment]
I just pushed the ship command.  Im not sure about the event manager stuff
but the game map should be contained in the game logic so should be easy to
look at.

**Comment by leighgarbs** [comment]
Yes Justin, the event handlers go in whatever class is interested in the event.  Then to get that event handler called whenever its corresponding event happens, it has to be associated with the event in an event manager using the event manager's addDelegate() function.  After that everything happens automatically, and the event handler gets called whenever that event is triggered in the event manager.  And yeah, binding an event to a handler is something that's best handled in an initialize function.

Christine, to make the "queue things onto the event manager if the delegates are void functions which I put inside of GameLogic.cpp" situation work, what you have to do is call the game logic event manager's addDelegate() function to associate the void functions with the event.  To properly do that the function has to have the right signature (returns void and takes a single const EventInterface& argument).  addDelegate() takes an EventDelegate to represent the function, so you have to jump through some hoops to get your function represented in a form addDelegate() will accept.  It will probably end up looking something like this ...

``` c++
void YourClass::yourEventHandler(const EventInterface& event)
{
  /* event handling happens in here */
}

/* then in YourClass::initialize this happens*/
event_manager->addDelegate(EventDelegate(std::bind(&YourClass::yourEventHandler, this, _1),
                           YourEvent::event_type);
```

I haven't compiled that, but that's the basic idea for associating a delegate with an event.  Since in this case the delegate is a member function of a class, you have to use std::bind to associate the class's member function (YourClass::yourEventHandler) with a specific object (in this case, this).  Queuing an event is another matter, and uses the queueEvent() event manager function.  The Game Programming Basics II slides have some more detail on this.

Want to meet briefly after class?  If you have your laptop I think I can give you some quick pointers.

**Comment by lifesurfeit** [comment]
I won't be able to meet after class, I have an interview scheduled after. I
can meet anytime after 4 though.

**Comment by leighgarbs** [comment]
I'm going to be back in Hampton this evening.  We could do a Google Hangout if that's any easier.  I think we can all use that since we have school-provided Google accounts.

**Comment by lifesurfeit** [comment]
Ok, that would be great. What time are you thinking of?

**Comment by jpszabo** [comment]
Unfortunately I have an exam from 8-10 pm tonight (also why I have mostly
been off this thread yesterday and today) but I can try to contribute
something afterwards if needed.

**Comment by leighgarbs** [comment]
Want to hangout at 7:30pm?

**Comment by lifesurfeit** [comment]
Ok, I'll call you then.

**Comment by leighgarbs** [comment]
Tell you what, make it 7:45

**Comment by lifesurfeit** [comment]
If you guys could take a look, I think I've got the basis for the GameLogic down. I wasn't sure what to do with the other TransactionHandlers other than TransactionCheck so I left them blank.

**Pull request merged**
