### PR TITLE
Gamepause

### PR DESCRIPTION
**Pull request by lifesurfeit**
Event handlers in rum_runners.cpp are bound to Transaction events and tell the game to pause. Fixes issue #16.

### CODE REVIEW

**Comment by leighgarbs** [comment]
Two things.  You don't really want to be using a #define constant this way.  The way to do it is to make game_time_factor a global variable.  Just define it outside main.cpp.

The other thing is that you don't need two separate event handlers for the success and fail events.  All you have to do is make one and register it with both events.

**Comment by lifesurfeit** [comment]
Ok, I'll fix that as soon as possible.

**Comment by lifesurfeit** [comment]
Updated.

**Comment by leighgarbs** [comment]
Looks good, anyone else?  Will merge after transaction_window.

**Comment by jpszabo** [comment]
Good with me.

**Pull request merged**
