### PR TITLE
Actor storage

### PR DESCRIPTION
**Pull request by leighgarbs**
Actor storage has been reworked to be more flexible and functional.  Actors are now stored in an ActorList in the game logic.  There is also a helper data structure that stores references to only the ports.  Accessors for the data structures containing the actors and ports have been created.  An accessor for the ship also now exists.  Existing game logic code was modified to account for the new actor storage method.  Actors now have their update() function called every frame.

Port creation is now done based on an init file (code/data/ports.txt) at runtime.  Ports were given a 'name' field to store their name, and this and the other existing port parameters are now filled in from the init file.  The actual parameters are just placeholders for now, not final.

### CODE REVIEW

**Comment by leighgarbs** [comment]
Justin feel free to branch this until we can get it to master.

**Comment by jpszabo** [comment]
I moved the map drawing capabilities into the HumanGameView and left a
branch with that on the repo. Tomorrow I'll probably branch this to get the
drawing of the actors working as well.

**Comment by leighgarbs** [comment]
I'll merge this in a bit unless there are objections ...

**Comment by jpszabo** [comment]
Great with me!

**Comment by mrfievel** [comment]
Sounds good!

**Pull request merged**
