### PR TITLE
Take a look and see what you think. The map and the sprites are re-scale...

### PR DESCRIPTION
**Pull request by jpszabo**
...d appropriately depending on the window resizing. However, the map remains centered if ONLY the window is vertically resized or ONLY if the window is horizontally resized. When the window is resized in both directions, the map is almost but not quite centered. If there are any obvious errs that I've made, let me know, otherwise I can show everyone what it's doing when we meet on Sunday.

I'm creating a pull request for this in case anyone wanted to test this branch for themselves. I think you would be able to do that without a pull request but I wasn't positive.

### CODE REVIEW

**Comment by leighgarbs** [comment]
It looks like it might be easier to set the size of the land and water sprites to (map_tile_size, map_tile_size) directly rather than scaling them.  Is there some reason that wouldn't work?

**Comment by jpszabo** [comment]
The sprite itself on the sprite sheet is 25x25 so that's the size it is
initially (taken care of in the call to setTextureRect). According to the
SFML Sprite class reference page, there should be a "Resize(float x, float
y)" method, but when I try to compile that I get a "no member named resize"
error.

**Comment by jpszabo** [comment]
Correction: I had been looking on the SFML 1.6 page where there was a
Resize method. On the SFML 2.0 documentation page, there is no option to
resize.

**Comment by leighgarbs** [comment]
Okay ... that makes sense.  It also makes sense that the map draws a bit small at some resolutions.  The map tiles have to have integer dimensions, but at some resolutions the window space the map is supposed to fit into divided by the number of map tiles might not come out to a round integer, so when we draw we lose that fractional data and the map is a bit small.

Initially I did take a brief look at how the scaling works.  The documentation for the sprite scale() function says it applies the supplied scale factor to the existing scale factor.  There is another sprite function called setScale() that reads like it applies the supplied scale factor to the original scale, which sounds more like what we want.  I tried setScale() and couldn't really see a difference.  If scale() was causing a problem I would think it would be really obvious, since the scale factors would be compounding on top of each other, but a quick look makes it seem like that's not happening.

Also, don't forget mapToWindow() exists now.  That can do all the map to window location translations for you.

Also also, be careful when merging master into this because it will conflict.

**Comment by leighgarbs** [comment]
Jim you merge master into this so we can get it to master by tomorrow's meeting?

**Comment by jpszabo** [comment]
It should be branched from master anyway but I'll do it tomorrow before the
meeting.

**Pull request merged**
