### PR TITLE
Made input dialogue more piratey.

### PR DESCRIPTION
**Pull request by mrfievel**
Just changed the dialogue on the input box to all be piratey.

### CODE REVIEW

**Comment by leighgarbs** [comment]
Looks good to me.  If it's okay with everyone I think this will have to be the last thing we do that goes into the demo movie, except for the sound, which I'll have to add in manually anyway.  I'll just pull those files off the sound branch to do that.

**Comment by jpszabo** [comment]
Sounds good to me!

**Comment by mrfievel** [comment]
Sounds good, I'm going to mess with balancing sometime tonight.

**Comment by jpszabo** [comment]
Might want to take a look at the new issue I just posted first...

**Pull request merged**
