### PR TITLE
Sound

### PR DESCRIPTION
**Pull request by lifesurfeit**
#53

### CODE REVIEW

**Comment by leighgarbs** [comment]
The rum runners theme is really good!  The waves and that tune that plays occasionally are perfect.  It does stop playing after a transaction, though.  We probably don't want that.

Couple other minor things ... All the .wav files for the sounds should be in the data directory, and I'd move the event delegates that play the sounds into the Sound class itself.  That way all the sound code is in the Sound class.  Oh, and you'll need to merge from master.

**Comment by lifesurfeit** [comment]
Ok, I'll make those changes.

**Comment by lifesurfeit** [comment]
Moved all event handlers into Sound and initialized Sound in main.

**Comment by leighgarbs** [comment]
Do you think you could move Sound into the HumanGameView?  That's probably the best place for it.

Also, I almost hate to ask, but do you think you could prepare a branch without all the spacing changes?  They're sort of unnecessary and cause conflicts, and it's difficult to look at the diff and see what changed.  Your stuff is contained mostly in the new Sound class.  The easiest thing to do would be to rebranch off master and add your stuff back in.

**Comment by lifesurfeit** [comment]
Yeah, sorry about that. The last few conflicts I had to do some re-editing.

Do you mean that I should initialize() within HumanGameView? I put it in
main because I had to add some functions from GameView into Sound to add
the handlers to the event manager in GameLogic from within there and felt
that it didn't need to be in HumanGameView anymore since it doesn't really
use anything there.

**Comment by leighgarbs** [comment]
Yeah, I'd put Sound in HumanGameView.  It makes the most sense there because the HumanGameView is where all the player-specific stuff goes.  Only the player cares about sound.

The HumanGameView has a pointer to the game logic, so you can copy that pointer into Sound when you initialize Sound in the HumanGameView.

**Comment by lifesurfeit** [comment]
Ok, I see.

**Comment by leighgarbs** [comment]
If it's causing problems I'd just leave it where it is for now.  It works
where it's at.

**Comment by lifesurfeit** [comment]
Actually I figured out what the issue was; I didn't have gamelogic initialized in Sound!

**Pull request closed without merging**
