### PR TITLE
New win lose merge

### PR DESCRIPTION
**Pull request by jpszabo**
Should be good to go.

### CODE REVIEW

**Comment by leighgarbs** [comment]
This looks pretty good, assuming we finish it off by getting game resetting working.  I guess the "game_over" flag was necessary to make YOU WIN or YOU LOSE display properly at the end?

Going forward what you're doing with resetStartValues() is probably what the initialize() functions we have everywhere should start doing.  Doing this now on this branch is probably out of scope, but I think we want to do that as part of the "implement game reset" task (#58).  There are some suggestions in the thread for that issue.

I played the game for a bit, it's interesting with the win/loss thresholds where they are.

Anyone else have anything?  I'll merge in a bit otherwise.

**Comment by leighgarbs** [comment]
Oh, there was one thing.  At certain window sizes the "time remaining" display doesn't show right.  Sometimes it's not visible, other times half of it is off the right side of the window.

**Comment by jpszabo** [comment]
Okay, I'll look into that. I'm gone for most of the day but I should have
time to fix that tonight or tomorrow. Then I'll get as much done with
resetting the values as I can before Tuesday, including adding the start
screen and everything.

**Comment by leighgarbs** [comment]
For now resetStartValues() works, I wouldn't mess with it on this branch.  Best thing to do would probably be to start transitioning everything to the initialize() functions when you start on #58.

**Comment by leighgarbs** [comment]
This resolves #56.  We need to start getting stuff to master so let's merge this and we'll track the time remaining indicator weirdness as another issue.

**Pull request merged**
