### PR TITLE
Start screen implemented. Game now starts paused, then GameRestartEvent ...

### PR DESCRIPTION
**Pull request by jpszabo**
...(which should really be renamed to GameStartEvent, Leigh was right) unpauses the game after the user presses spacebar. Scales to fit full screen, which doesn't look great but good enough for now.

Will continue to add screens.

### CODE REVIEW

**Comment by jpszabo** [comment]
Added screens for win and lose conditions. I'll be out for a little while but when I get back I'll work on the other two screens. I can really make as many as needed but hopefully that's just two (brief explanation of story and mechanics).

**Comment by mrfievel** [comment]
I think that'd be enough screens.

**Comment by jpszabo** [comment]
I had a good idea too. So the first screen will be the basic story and the second screen will act as kind of "instructions", like it'll say WASD to move, land on a port to buy or sell rum, etc. Then once you start the game, that second screen will be accessible at any time via the "i" key as like an instructions page. Then you press space to get out of it. In terms of implementation, it'll be a little tricky because right now, advancing passed that screen would cause the game to start, but that isn't what we'd want for just looking at the instructions. That can probably be handled with events though. Also, I'll work on it if we have time, it isn't a key feature but it would be pretty cool/look professional.

**Comment by mrfievel** [comment]
That sounds cool if you find the time for it.  Maybe just make the button be spacebar instead of i though and then it would also serve as a pause screen?

**Comment by jpszabo** [comment]
That's a good idea. Here's my story screen. I haven't put it on the branch yet but I will later tonight.
screen shot 2014-11-23 at 5 42 39 pm

**Comment by mrfievel** [comment]
Good job, that looks great!  Really glad the actual shark made it in there.

**Comment by lifesurfeit** [comment]
Looks good!

**Comment by jpszabo** [comment]
I thought about trying to put it in the losing screen but I haven't found a
place for him yet. He works on the story screen though. Glad you like it!

**Pull request merged**
