### PR TITLE
Enemies

### PR DESCRIPTION
**Pull request by mrfievel**
A first shot at enemies.  Changes a lot of stuff.  Includes two enemy pirates that animate correctly and are green when patrolling then red when pursuing you, plus they speed up a bit when red.  If they would run into you they instead take 2 rum, or 2 gold for every rum they can't take (if you have 0 rum they take 4 gold, if you have 1 rum they take it and 2 gold).  

There are some notable problems with this build that I'm working on, for example the path finding algorithm is very stupid and can lead to the ships just kind of going in circles.  Also the collision detection is very wonky and the rum penalty can happen very quickly because there's no window of invincibility.  On the next iteration I'm going to obfuscate the pathfinding instead of fixing it by having the ship randomly choose a new patrol every so while and definitely add some kind of invincibility window when an enemy runs into you, plus probably make them pause for a second.  I'll also work on a merchant you can chase which should be very easy with what I've built already and hopefully get the kraken working, which I have a  base for but has a few complications.

### CODE REVIEW

**Comment by leighgarbs** [comment]
Looks like Pirate.hpp is missing ...

``` console
/Users/leigh/cs420-game/code/include/GameLogic.hpp:16:10: fatal error: 'Pirate.hpp'
      file not found
#include "Pirate.hpp"
         ^
1 error generated.
```

**Comment by mrfievel** [comment]
Not sure how that happened but just added it in.

**Comment by leighgarbs** [comment]
More compile issues ...

The top of Pirate.hpp looks like

``` c++
#if !defined PIRATE_HPP                                                            
#define PIRATE_CPP 
```

It checks for PIRATE_HPP but defines PIRATE_CPP.  Also it looks like Pirate.cpp is missing too.

**Comment by mrfievel** [comment]
Fixed both problems.

**Comment by leighgarbs** [comment]
After a quick look it looks like the enemies are copied into the AIGameView and then they have their copied states updated in the AIGameView update, then that info is passed back to the game logic with the ActorMovedEvent.  Since the game logic owns all the actors, structurally it makes a lot more sense for the enemies to have their states updated in the game logic.  It also looks like, except for position, the updates to the copied state of the enemies currently performed in the AIGameView never makes its way back into the game logic.

The best thing I can see to do here would be for the AIGameView to obtain all the information necessary to direct the enemies (copying the enemies list as part of this works, but going through a pointer instead would avoid the copy), then come up with commands for the individual enemies.  Those commands would be passed back to the game logic via an event of some kind.  Right now we have a ShipMoveCmdEvent, so an EnemyCmdEvent springs immediately to mind.  That would have commanded updates to state for an enemy.  Then the game logic takes these commands changes enemy state and position appropriately.

The ActorMovedEvent should really only be used to notify that an actor has moved, not to actually perform a move.

AIGameView is updated after the game logic ... for consistency we probably want to update all the game views at the same time.

**Comment by mrfievel** [comment]
Yeah, looking at it I'm not using a pointer like I thought I was.  Working on that right now.  I used the ActorMovedEvent just because it wasn't actually being used by anything but thinking about it some of the stuff Christine and James are working on might so I'll create a new one and use that.

**Comment by mrfievel** [comment]
Alright, I changed it so AIGameView is specifically using a pointer to GameLogic's list instead of a copy.  I'll make the new AICmdEvent and fix ActorMovedEvent in a second.  Thinking about it a handler for ActorMovedEvent would probably also be a good place to put the rum damage so it doesn't happen inconsistently.  

Also, this made me realize what might be a problem.  I made my EnemyList getter based off the ones already there (ActorList and PortList) which means there might be similar problems with the HumanGameView using the ActorList and such.

**Comment by mrfievel** [comment]
Alright I think I fixed all the big things with this last build.  The AIGameView now just uses a pointer instead of its own copy of the enemy's list.  It now uses a specific AICmdEvent instead of the ActorMovedEvent.  Also, when an AI enemy moves it now queues its own ActorMovedEvent onto the event manager.

**Comment by leighgarbs** [comment]
There's still a bit of weirdness with how the AIGameView directly updates the state of the enemies in the game logic, but we might just want to deal with this for now.

This move time check in AIGameView::moveActors ...

``` c++
// only sends move command if enough time has passed
if (enemy->getMoveTime() > enemy->getMinMoveTime()) {
  sf::Vector2i temp = minMaxMove(enemy);
  AICmdEvent* ai_event = new AICmdEvent(enemy->getActorId(), temp);
  getGameLogic()->getEventManager()->queueEvent(ai_event);
  enemy->setMoveTime(0.0);
}
```

... implements a game mechanic and probably belongs better in the game logic.  It's fine if the AIGameView spams the game logic with move commands, the game logic will just not do the move if it's not time yet.

Does the AIGameView have to be updated after the game logic?

Other than these things this looks fine.  This is a big change so I think we want to get everyone's okay.  Jim, Christine, what do you think about this?

**Comment by mrfievel** [comment]
Alright, I moved the move command check to the game logic and put the AIGameView update after the HumanGameView, that was just random when I was first making it.  Besides that the only updating of game logic i think the AI game view does directly is setting seeks which is probably not ideal but would be a decently large amount of code to change.  I can work on that after I get the path finding and collisions working  better though if we all want.

**Comment by jpszabo** [comment]
Everything looks pretty good to me! I can't wait to see it in the game.

**Pull request merged**
