### PR TITLE
Enemies update

### PR DESCRIPTION
**Pull request by mrfievel**
Don't actually merge this yet, just wanted to send out the e-mail.  I messed with the AI pathfinding quite a bit and I think it looks much better.  It's still not implementing A\* or anything but the only time I've seen it get stuck was on Antigua and corners.  It also occasionally asks for a new waypoint to patrol to and that has gotten it out of everything except for Antigua after me running it for like 15 minutes with a fast speed.  I'm gonna start working on consistent rum damage now.  Let me know how you guys think this AI looks alright.

### CODE REVIEW

**Comment by mrfievel** [comment]
Added merchant and kraken.  Should be good to look at for merging now.  Note doesn't have kraken sprite yet, just uses red and green squares, just takes changing 4 lines of code to fix though.

**Comment by mrfievel** [comment]
Kraken sprite implemented!  This is merged with the recent master and is a near final build for enemies I think.

**Comment by jpszabo** [comment]
How does it look?

**Comment by mrfievel** [comment]
The sprite looks pretty good I think very sinister the tentacle movement is
weird sometimes but not sure how I could make it better easily.  You can
pull it and take a peek.

**Comment by jpszabo** [comment]
I was only asking because the sprites got a little distorted when I shrunk
them to 25x25, I think they looked better before. Also have you made any
progress on the window of invincibility after hitting a pirate?

**Comment by mrfievel** [comment]
Oh yeah they look centered and such.  And yeah I got that working before
the new enemies, you're invincible for 3 seconds and turn good after being
damaged.

**Comment by mrfievel** [comment]
Turn gold*, and they also don't look distorted.

**Comment by mrfievel** [comment]
Good job on the kraken sprite and thanks for putting it up!

**Comment by jpszabo** [comment]
Awesome! Great job.

**Comment by leighgarbs** [comment]
I can only see two potential issues with the colors.  The black pirate ships are hard to identify when they're animating a certain way, for instance up or down.  They almost look like the kraken tentacles, but fatter.  Also, when the merchant ship is hit and turns blue, it looks a lot like the pirate ships.  What if the pirate ships were gray and the merchant ship turned a lighter blue?

**Comment by mrfievel** [comment]
I changed the pirates to be gray and the empty merchant ship now turns cyan instead of blue.  It's kinda hard to see the merchant ship when it's like that but I think it's ok since you can't raid it then anyway.

**Comment by leighgarbs** [comment]
I like the gray pirates, you can see the ship texture underneath.  It's hard to see when the merchant ship changes color, but as far as the functionality goes though I think we're okay with this so I'll go ahead and merge.

**Pull request merged**
