### PR TITLE
Framework

### PR DESCRIPTION
**Pull request by leighgarbs**
Here's a first hack at all the framework logic, view, and actor code we need to get started.  Main creates the game logic and a human game view, and updates them in the main loop.

We may want to consider having the human game view draw after the game logic updates ...

Let's all chime in on this quickly so we can get it to master as soon as possible, that way it's easier for everyone to start using.

### CODE REVIEW

**Comment by leighgarbs** [comment]
Of course if anyone sees anything that should change, just point it out.

**Comment by mrfievel** [comment]
Looks like a good start to me!

**Comment by leighgarbs** [comment]
Christine, Jim, what do you think?

**Comment by lifesurfeit** [comment]
Looks good!

**Comment by jpszabo** [comment]
Good with me, sorry I've been away from my email all day today.

**Pull request merged**
