### PR TITLE
Sound2

### PR DESCRIPTION
**Pull request by lifesurfeit**
#53 Should be good to go!

### CODE REVIEW

**Comment by leighgarbs** [comment]
It doesn't build for me ...

**Comment by lifesurfeit** [comment]
What's the error?

**Comment by lifesurfeit** [comment]
Ah I figured it out... forgot to include some data files!

**Comment by lifesurfeit** [comment]
Let me know if you still can't build.

**Comment by leighgarbs** [comment]
Sound.hpp included GameLostEvent.hpp, which included HumanGameView.hpp, which has Sound in it but was undefined because the compiler never fully parsed the original Sound.hpp include.  Getting rid of the references to HumanGameView in GameLostEvent.hpp fixed that.

The game was still looking for tada.wav, so I added that back in.  That got everything running nicely.

Resolves #53

**Pull request merged**
