### PR TITLE
Design update

### PR DESCRIPTION
**Pull request by leighgarbs**
This is the updated design document.  We already talked about this so I'll go ahead and merge ...

### CODE REVIEW

**Comment by jpszabo** [comment]
Hey all,

I've converted the map to using sprites/textures instead of just drawing
colored rectangles. I haven't quite figured out how to make it less blocky
looking but I'll keep thinking about it.

I've also found a nice sprite sheet with some wooden ships from different
angles. I put an 'S' on the map so that it would draw, and it looks good
but a little small. Should I add a drawShip  and draw Port method to the
Ship and Port classes?

**Comment by leighgarbs** [comment]
Great!  If you have it on a branch we can pull it and take a look.

So, you have the ship in the map?  The ship will take the place of a tile
then, right?  I think we want to keep the map knowing only land and sea
tiles, and draw the actors separately.

According to Dr. Peers, it's tempting to have the actors know how to draw
themselves, but not a good idea because then there's drawing code in the
game logic. The recommendation there was to have the game view store
positions and draw separately.

Leigh

Does the

**Comment by jpszabo** [comment]
I'll put it up a little bit later tonight. I also wanted to find or make
some sort of sprite for the ports but I didn't get a chance to do that just
yet.

I put the ship in the map just as a test but I knew it didn't belong there
for the actual game. I can leave it in for you to see or I can take it out,
it's up to you.

I can add the code to draw the ship and ports to the game view if everyone
is cool with that.

**Comment by jpszabo** [comment]
I found a sprite to use for the ports. It looks kind of like a wooden deck,
which I think is pretty fitting. The color is easily changeable if we
wanted to implement our orange and purple color scheme as we had previously
discussed, or it probably wouldn't be that hard to just draw a sprite of a
'B' or an 'S' over top of it to indicate "Buy" and "Sell" port. We can
discuss this on Sunday or in the email thread, whichever.

Again, I added a 'P' to the map just as a check, but I'll try to implement
a drawPort and drawShip method in the game view, if that's what we think is
best. I can also move the drawMap function to the game view class, just to
have them all in one place. Just let me know.

Have a good night!

**Pull request merged**
