### PR TITLE
Reinitialize

### PR DESCRIPTION
**Pull request by jpszabo**
Reinitialization of all actors works upon restarting game. This will need to be updated once Justin's Kraken and Merchant enemies get merged into master, but it works for now.

### CODE REVIEW

**Comment by leighgarbs** [comment]
Yeah actually this looks good.  You'll have to merge from master before we can merge.

**Comment by jpszabo** [comment]
My plan is to make new initialize functions for each of the new actors
(including each tentacle for the Kraken). Sound good?

**Comment by jpszabo** [comment]
Never mind, I'm just going to make one for the merchant and one for the Kraken, that will work fine.

**Comment by jpszabo** [comment]
Sorry for the delay, the first time I tried to merge things got a little hairy. I got it right the second time though.

**Comment by leighgarbs** [comment]
Actually it looks like this bit of code at the bottom of GameLogic::initialize ...

``` c++
       // Register the proper handler for collision detection                     
    event_manager.addDelegate(                                                     
    EventDelegate(std::bind(&GameLogic::CollisionEventHandler,                     
                            this,                                                  
                            std::placeholders::_1)),                               
    ActorMovedEvent::event_type);
```

... never made it onto your branch from the merge, and the effect is that the ship doesn't suffer any of the effects of colliding with anything.  I tossed it in and collisions worked again, but I didn't commit to your branch.  I think that's the right fix though.

**Comment by jpszabo** [comment]
Oh, yeah that's pretty important. I'll put that back in. There were huge
merge conflicts, they had two initialize() and update() functions, along
with lots of other mess. I wasn't sure what that one was for.

**Comment by jpszabo** [comment]
Just re-pushed the branch.

**Pull request merged**
