### PR TITLE
Map with sprites

### PR DESCRIPTION
**Pull request by jpszabo**
Added the sprite file with all sprites I have compiled so far. Map is drawn using blue and green rectangles from sprite file.

### CODE REVIEW

**Comment by leighgarbs** [comment]
It's probably good if we start putting all our non-code stuff into a separate folder.  How about we create a 'data' folder in the code directory and put the sprites in there?

Also, this branch has consistent_map_coordinates on it already.  Did you mean that?

**Comment by jpszabo** [comment]
We can put the sprites and map text file in the 'data' folder.

That was a mistake, I wasn't thinking when I was branching in my local
directory. I branched off of 'consistent_map_coordinates' instead of
'master'.

**Comment by jpszabo** [comment]
Would you like me to fix this branch so that it does not include
consistent_map_coordinates?

**Comment by leighgarbs** [comment]
Nah, that's alright.  We can just use this branch and ignore consistent_map_coordinates.  It would be good to at least get the sprites into a 'data' folder before we merge though.

**Comment by jpszabo** [comment]
Just pushed again, I'll create the pull request now if you want me to.
Added the 'data' folder with the map files and the sprites file, and make
the appropriate changes to GameLogic.cpp, HumanGameView.cpp, and Map.cpp.

**Comment by leighgarbs** [comment]
Looks good.  Justin, Christine, what do you think?

**Comment by leighgarbs** [comment]
Christine, Justin, are you both okay with this?  I'll go ahead and merge this in an hour or two unless there's any objection.

**Comment by mrfievel** [comment]
Looks good

**Pull request merged**
