### PR TITLE
PIRATE FONT

### PR DESCRIPTION
**Pull request by mrfievel**
The most important update, pirate font.  Just threw this in real quick if anyone wants to use it, especially with the intro and outro stuff you're working on James.

### CODE REVIEW

**Comment by jpszabo** [comment]
Yes!

**Comment by leighgarbs** [comment]
Do we want to merge just the fonts on this branch so we have them?  I don't know that we want the code change, but if it helps to have the fonts sitting somewhere in the data directory we could do that.

**Comment by jpszabo** [comment]
Sure. It could help me with my screens. Right now, I'm creating separate
.pngs for each, but it might be best if I could just have one "template"
screen and write text on it using one of the fonts, so that we aren't
loading up a bunch of textures.

But I'm also good doing it the way I'm doing it, so either way it's not a
bad idea to include the font files.

**Comment by leighgarbs** [comment]
Justin's got the fonts on an upcoming branch so I think we'll just close this one out and get the fonts as part of that branch.

**Pull request closed without merging**
