### PR TITLE
Draw actors

### PR DESCRIPTION
**Pull request by mrfievel**
The game view now draws the actors as test blocks of color, red for port and yellow for ship.  This includes everything James did in moving the map draw to the human game view but not the actor sprites because both files modified the HumanGameView and I didn't want to deal with that.  The key presses now also queue up a ship command event but the ship doesn't actually move, I even printed out the events data to make sure it was all correct and it is.  Looking at the code my guess is that something weird is happening with the game logic using a pointer called ship seperate from the actor list that I'm drawing from, but that's just a guess.

### CODE REVIEW

**Comment by mrfievel** [comment]
Hmm I tried doing a test printout on the ShipMoveHandler itself and its not firing at all, so I assume I'm not queueing up the ship move properly.  Don't know what's wrong though, it's all on lines 122 and 123 of the HumanGameView if anyone wants to take a look.

**Comment by mrfievel** [comment]
Figured it out I was using the game views event manager not the logics you can move now!  Just really fast, gotta figure out who's responsible for ship movement speed (I assume game logic).

**Comment by jpszabo** [comment]
Exciting stuff! Great work.

**Comment by leighgarbs** [comment]
Yeah, looks good.  You can move the ship off the map but that's an easy fix.

**Comment by lifesurfeit** [comment]
Great!

**Pull request merged**
